### ISSUE TITLE
firebase example.

### ISSUE THREAD

**Issue by ciumexan** [gabrielreiscom/hapi-firebase-auth#1]
AssertionError [ERR_ASSERTION]: Authentication strategy firebase uses unknown scheme: firebase
    at new AssertionError (internal/assert.js:394:11)

on v17 do you have a working example for this?

My setup test looks like:

`'use strict';

const Hapi = require('hapi');

const HapiFirebaseAuth = require('hapi-firebase-auth');

// Initialize the default app
const admin = require('firebase-admin');
const firebase = require('firebase');

// Create a server with a host and port
const server = Hapi.server({
    host: 'localhost',
    port: 8000
});

// Add the route
server.route({
    method: 'GET',
    path: '/hello',
    handler: function (request, h) {

        return 'hello world';
    }
});

// Include auth strategy ... obfuscated for exampling...
server.auth.strategy('firebase', 'firebase', {
    credential: {
        projectId: '___',
        clientEmail: '___',
        privateKey: '___',
        databaseURL: '___'
    }
})

// Start the server
const start = async function () {

    await server.register({
        plugin: HapiFirebaseAuth
    });
    
    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log('Server running at:', server.info.uri);
};

start();`

**Comment by GabeReis** [comment]
Hi @ciumexan. I'll try to push a working example this weekend.

**Comment by ciumexan** [comment]
thanks looking fwd to, I am looking to use this with a swift (ios) app.

**Comment by ciumexan** [comment]
any news on this? thanks.

**Comment by GabeReis** [comment]
Hey, sorry I'm super busy at work but I'll check this when I have a chance.

**Comment by ciumexan** [comment]
any chance? I am looking to see how can i use same token from swift

**Comment by ciumexan** [comment]
you can close this. thanks.
